### ISSUE TITLE
Kubernetes Community Day London 2020

### ISSUE THREAD

**Issue by oicheryl** [cncf/kubernetes-community-days#170]
### Submission checklist:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [x] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Minimum of 3 sponsors
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page

**Comment by christinevblum** [comment]
Welcome @oicheryl! Can you make sure organizers have signed off on the event guidelines and code of conduct?

**Comment by oicheryl** [comment]
@jmickey @dlectronique Please read https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing and thumbs up this comment to sign off.

**Comment by blixtra** [comment]
@oicheryl We were talking with JetStack about doing a KCD In London in May of next year. Do you think there is room for collaborating on making that happen?

**Comment by oicheryl** [comment]
@christinevblum Organisers have signed off.

@blixtra Have you begun organising? May next year is very tight.

**Comment by blixtra** [comment]
We feel comfortable with being able to pull it off. We have a team that focuses on events. We're also planning on doing one in Berlin at a similar time and feel that having those close together has benefits for those coming from abroad.

**Comment by dankohn** [comment]
@blixtra We added a requirement https://github.com/cncf/kubernetes-community-days/pull/175/files (it accidentally disappeared from earlier drafts) that organizers need to be local. We want to avoid situations of having organizations "squat" on multiple KCD locations.

Also, my experience is that events run by single organizations can naturally move faster than KCD-like events where some consensus is required.

**Comment by blixtra** [comment]
Ok, that complicates things a bit for our Berlin event. For Berlin, we intended to have Loodse (Hamburg) and JetStack (London) joining. For London, JetStack would have been the local lead with us doing lots of the logistics since we have that experience. So it looks like neither Berlin nor London would work in those forms.

Also, I'd assume that you will often find that there will often have lead organizers as there are organizations that simply have a lot of the processes and ppl in place to pull it off. I know with some of the folks we spoke with that was something that was very welcome.

Also, we have ppl working remotely in several places, including myself (Colorado). We were interested in doing KCD in some of those locations. For example, I'd be happy to be an organizer for one in the Denver/Boulder area. But even if I put myself as an organizer, I will get lots of help for may part from our events team which is also a distributed. It's a shame that in that case those folks doing some of the organization couldn't be named.

Personally, I think the requirement for having ppl be local is good. For example, I think the Kubernetes Meetups got squatted quickly and it prevented a lot of local organizing. We started the Cloud Native Computing Meetup for that reason. But I think having KCD being lead by a local organizer and having others join who may not necessarily be local is a better way of dealing with that.

**Comment by dankohn** [comment]
Thanks for understanding where we’re coming from. I think we genuinely need each organizer to be local *and* actively involved but nobody should hold it against them if they also get help from other staff at their company. But, the organizer position belongs to the person, not the company, if, for example, people change jobs.

**Comment by dlectronique** [comment]
Just my thoughts - Local community days should be run by the local community, like DevOpsDays. We have enough folks on the ground here (from different organisation) who are willing to help out with KCD London, who are experienced event organisers in the community. Having just completed a succesful DevOpsDays London last week, I think we're good for experienced crew members :)

**Comment by blixtra** [comment]
Sorry, for coopting the issues. I was wondering more now about Berlin and Denver. I think some of the confusion comes because for Berlin, we [were point to work](https://github.com/cncf/kubernetes-community-days/issues/117#issuecomment-532366783) with folks that were not from Berlin for the Berlin event.
I'll take that to the Berlin issue, though. :wave:

**Comment by oicheryl** [comment]
@blixtra Thanks for understanding and sorry for any confusion caused.

@dlectronique and @jmickey are both heavily involved with the London and UK tech community and have organised conferences with 100s of attendees, so I am very confident in their skills, experience and commitment to deliver a fantastic KCD London.

**Comment by christinevblum** [comment]
@oicheryl do you have 3 sponosrs for your event? Once we get your 3 sponosor names your team will be signed off to start your event pages.

**Comment by oicheryl** [comment]
@christinevblum JFrog, WSO2 and xMatters have confirmed they would sponsor a Kubernetes Community Day London.

**Comment by christinevblum** [comment]
@oicheryl thanks! I will move you to approved to build your site. Let me know if you want to schedule a kick-off call this week.

**Comment by oicheryl** [comment]
Sure, please schedule a call  on Thursday or Friday using https://www.oicheryl.com/bookme.

**Comment by iennae** [comment]
Hey folks, 

Just wanted to circle back to see where you folks are in the process.

**Comment by dlectronique** [comment]
> Just wanted to circle back to see where you folks are in the process.
we're about to confirm our venue and date :)

**Comment by dariakg** [comment]
Hi guys! I'm wondering if you need extra hands for this? As an organiser or a sponsor?

**Comment by oicheryl** [comment]
Hi @dariakg - yes to both! I'm hoping the venue & date will be confirmed next week, so everything else should kick off very soon. I would love to get your help with both sponsorship and organising.

Please drop your name into https://kubernetesdays.london/ (select Sponsoring and Volunteering as the interests) and we'll take it from there.

**Comment by KTan1226** [comment]
Hi KCD London team. Just checking in to see how your website is coming along. I'm happy to help you get started.

**Comment by jmickey** [comment]
Hi @KTan1226 we're just waiting confirmation on the venue and event date before we submit the website PR. Hopefully we should have that completed next week!

**Comment by dariakg** [comment]
@oicheryl I've submitted the form in the link you sent but haven't gotten a reply so just wanted to check in and see if it came through

**Comment by oicheryl** [comment]
Pending paperwork, we have a venue and date for KCD London!  

@dariakg yep, I'll email you in just a moment.

**Comment by KTan1226** [comment]
Great @jmickey- just let me know if I can help! :)

**Comment by KTan1226** [comment]
Hi London team. I wanted to reach out on creating a sponsorship email alias/subgroup. We recommend that KCD organizing teams use a main alias or subgroup rather than their own email so that we can have a record and ability to change the organizers in future years. We are happy to provide one (like kcd-bouvet-island-sponsors@lists.cncf.io) if you are interested.

**Comment by jmickey** [comment]
Hi @KTan1226 

Sure, we would happily use a sponsor email alias.

**Comment by KTan1226** [comment]
Great @jmickey- I will create the alias and share it with you shortly.
