### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#19]
Luc - can we update the events page: https://kubernetes-community-days.netlify.com/events/

This page should be set up like a table with that date of the event, the Name of the event, City of the event, and “Learn More” with a link to the event page.
I'd like it to look like OpenStack Days: https://www.openstack.org/community/events/openstackdays#tab=events_tab

**Comment by dankohn** [comment]
What if we instead we kill the events page and just have the list live on the homepage, as it does on https://devopsdays.org.

Also, I think best practice from usability is just to have the event name link to the event rather than needing a learn more button.

I would support adding an extra column that would be "city, country".

**Comment by christinevblum** [comment]
Dev ops has an events page too. I am happy to kill the double listings. I would like to have a section for "Coming Soon" (as I think that will be most of them for now). I would like the city

**Comment by dankohn** [comment]
I'd like to skip the events page and have the site avoid duplication. I'm hesitant to support a Coming Soon because we don't have clear rules on what would justify getting listed there. Instead, I'd like organizers to find each other using GitHub issue templates as defined in #7. Here are two templates for patterns you can emulate:

https://github.com/cncf/cluster/blob/master/.github/ISSUE_TEMPLATE.md
https://github.com/cncf/landscape/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Closing now, unless we decide to add an events page later.
