### ISSUE TITLE
Adjust top-level menus

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#21]
Please remove the About and Events menus from the root pages. The content of both pages will just be embedded in the homepage.

**Comment by lucperkins** [comment]
@dankohn So there won't be a `/events` page that lists all of the events?

**Comment by dankohn** [comment]
Lets leave out for now. We could always add later if the homepage becomes too full.

**Comment by cjyabraham** [comment]
My 2c:
What about using this language for the menu rather than the present continuous:
**Attend | Organize | Speak**
**Attend** link to the home page with the about info and event listing.  You could have a toggle to show past events and not have them visible by default to limit the amount of info initially present.

**Comment by dankohn** [comment]
Attend seems redundant.

**Comment by cjyabraham** [comment]
I don't feel too strongly about it, however, it re-enforces a nice MECE set of actions that one might be interested in doing with a Kubernetes Day.

**Comment by lucperkins** [comment]
I'm also a fan of the verb-driven menu, personally. FWIW.

**Comment by dankohn** [comment]
This is done.
