### ISSUE TITLE
KCD Washington, DC 2021

### ISSUE THREAD

**Issue by xmulligan** [cncf/kubernetes-community-days#381]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the CNCForum location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [x] Videos uploaded to Youtube and linked to event page

**Comment by CathPag** [comment]
Here you go:

 - No other Kubernetes Community Day event in the same region: correct
 - Minimum of 3 organizers from 3 different organizations: Kublr, EastBanc Technologies, The American Red Cross, Boxboat, Buoyant
 - Each organizer lives in or just outside of the CNCForum location: yes
 - At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer: yes
 - All organizers agree to follow the event guidelines and CNCF Code of Conduct: yes
 - Minimum of 3 sponsors committed: yes 
-  Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses: EastBanc Technologies 
- Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event: yes
-  Agree to use Cloud Native Community Groups for registration, scheduling, and event website: yes
-  Agree to use SM Apply for CFP: yes
-  Event date and time has been chosen: Nov 4, 2021 from 1 to 5 pm (we'll start with a half day)
 Added usernames for CNCF Slack for all organizers so that we can add you to the #kcd-organizers channel
 Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
 Organizer email alias has been created: all already set up

Expected Number of Attendees: 150-200
- Organizer 1: Catherine Paganini, Buoyant, Head of Marketing, catherine@buyoant.io, Catherine Paganini
- Organizer 2: Jason Morgan, Buoyant, Developer Evangelist, jason@buoyant.io, jmo
- Organizer 3: Brandon Mitchel, Boatbox, DevOps Solution Architect, docker@bmitch.net, Brandon Mitchel
- Organizer 4: Matthew Cascio, Executive Director, matthew.cascio@redcross.org, Matthew Cascio
- Organizer 5: Michaela Lozano, mlozano@eastbanctech.com, Marketing Associate, michaela.williams
 
- Sponsor 1: Kublr
- Sponsor 2: EastBanc Technologies
- Sponsor 3: BoatBox
- Fiscal sponsor that will accept payments: EastBanc Technologies

**Comment by xmulligan** [comment]
Thanks, I've just updated the issue and added Brandon to the slack channel. I couldn't find Michaela in the CNCF slack. Does she have a user?

I'll work on getting you access to SM Apply and CNCG tomorrow

**Comment by CathPag** [comment]
Thank you, Bill! They are all in the #kcd-dc-organizers channel, so yes. 
....and I just checked and she's already in the channel :)

**Comment by xmulligan** [comment]
@CathPag I just updated the email forward to everyone's new emails. Seems like quite a few have switched companies ;) organizers-dc@kubernetescommunitydays.org

**Comment by xmulligan** [comment]
@CathPag I've added you as an admin to the SM Apply account, let me know who else should be added. You have a copy of the KCD Berlin set up, but feel free to edit as you need

**Comment by CathPag** [comment]
Yes, thanks for catching! It's me and Jason (jason@buoyant.io) who switched jobs. What's the SM Apply account?

**Comment by xmulligan** [comment]
SM Apply is to help you organzie the CfP

**Comment by xmulligan** [comment]
I've added both @CathPag and Brandon to the https://community.cncf.io/kcd-washington-dc/ as organizers. Jason, Mattew, and Michaela don't seem to have accounts on the platform yet. Once they do, I can add them

**Comment by CathPag** [comment]
Thank you! I'll ask them to sign up.

**Comment by xmulligan** [comment]
Perfect, you can find out more about setting up the platform here https://github.com/cncf/kubernetes-community-days/blob/master/content/organizing-platform-help.md

**Comment by sudo-bmitch** [comment]
Couple corrections on my entry, Mitchell has 2 Ls, and BoxBoat capitalizes both Bs:

Organizer 3: Brandon Mitchell, BoatBox, DevOps Solution Architect, docker@bmitch.net, Brandon Mitchell

**Comment by xmulligan** [comment]
@sudo-bmitch I've just updated it for you.

@CathPag how is the event progressing? Is there anything you need my help with? When do you think you will be ready to go live?

**Comment by CathPag** [comment]
@xmulligan, when I set it up, I didn't know how the platform worked and thought the page was the event. Just published it. We'll all meet soon to kick-off event planning. Since we won't have sponsors, it's a little easier this time around, but thanks for checking! 

I do have one question: Do you know what these red lines on the dashboard mean? I'm part of three chapters (KCD DC, Linkerd, and our DC meetup). 
<img width="238" alt="Screen Shot 2021-04-08 at 7 36 34 AM" src="https://user-images.githubusercontent.com/74001907/114020064-29fff780-983d-11eb-8020-9390301494e7.png">

**Comment by xmulligan** [comment]
@CathPag no worries, maybe that should be more clear. It is live on the site now. Let me know if there is anything else I can help with!

The dashes are supposed to show an overview of the chapter activity for the month. Red = no event, Green = event, and Grey = wasn't live then. I think it shows the current month in the middle so +/- two months on either side. It was supposed to give you a quick overview how of the health, but I'm not sure how helpful it actually is.

**Comment by CathPag** [comment]
Thanks for clarifying, @xmulligan! Yeah, I find it more confusing than helpful. Good to know, I'll just ignore moving forward :)

**Comment by xmulligan** [comment]
@CathPag I've moved this into execution now. Do you know when the CfP will be launch and do you need any more help from me?

**Comment by CathPag** [comment]
Thanks, @xmulligan. @sudo-bmitch and Jason Morgan (whom I can't tag here for some reason) handle the CFP. Brandon, any update? Do you need help from Bill?

**Comment by sudo-bmitch** [comment]
I'm hoping to get a second set of eyes on the CFP before releasing to the public. I think Jason is working on that, but haven't seen an ETA from him. @xmulligan if there's any documentation or guides on setting up our CFP's in smapply, I'm happy to go over that. It was mostly poking through menus and hoping I updated all the fields for our name and date, but very possible I missed some nested setting a few layers down. I also want to test the form before publicly advertising it.

**Comment by xmulligan** [comment]
@sudo-bmitch here are a couple links for you and I'll also add these to the documentation on Github
Testing your Program: https://help.smapply.io/hc/en-us/articles/115001609313-Testing-your-Program
Help Center Resources: https://help.smapply.io/hc/en-us
Training Videos: https://help.smapply.io/hc/en-us/categories/115000187973-Implementation-Training-Videos
Build + Launch: https://help.smapply.io/hc/en-us/sections/115000405794-Build-Videos

Let me know if that helps!

**Comment by xmulligan** [comment]
@CathPag I just wanted to check in with you now that you are about half way through the CfP. Is there anything you need from CNCF?

Also can you provide me access to your Twitter account? We are trying to centralize access to we can have better continuity

**Comment by CathPag** [comment]
@sudo-bmitch and @JasonMorgan, could you please provide Bill with an update regarding CFPs? Not sure where we are at.

Regarding the Twitter account, I'll have to as Michaela Lozano (Williams).

**Comment by sudo-bmitch** [comment]
@xmulligan We're still thin on submissions, but this is my first time on reviewing the CFP's and it may be normal for everyone to wait until the last minute (I know I would when I submit them). Any additional publicity is welcome.

**Comment by xmulligan** [comment]
@sudo-bmitch from our experience, people always wait until the last minute. The schedule for KubeCon NA is coming out this week so maybe you can pick up some of the rejects from there. If you have a tweet, we would be happy to include it in KubeWeekly

**Comment by xmulligan** [comment]
I would also like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

**Comment by CathPag** [comment]
Sure. our next meeting is Aug 11 at 4:30 pm ET. Are you back in Europe or still in the US. If the former is the case, we'll have to find an earlier time.

**Comment by xmulligan** [comment]
I am in Europe until KubeCon. If there is an earlier time, that would be awesome. We can also do later this month in case there isn't a time next week. I don't have anything urgent, just want to make sure I can help you in the process :)

**Comment by xmulligan** [comment]
188 attendees https://www.youtube.com/playlist?list=PLj6h78yzYM2MoDMCUMVdCVVcTVe9BbX9L
