### ISSUE TITLE
KCD Berlin 2022

### ISSUE THREAD

**Issue by cpanato** [cncf/kubernetes-community-days#390]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Date and Time:

 - CfP open and close dates: February 9 - May 26, 2022

 - event: Wed, 29 Jun 2022, 10:00 – Thu, 30 Jun 2022, 16:00 CEST

### Event type: 
- in person

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Organizer email alias has been created

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Organizer 1:
Chris Kuehl, Kinvolk, CEO, chris@kinvolk.io + Lexi Nadolski, Kinvolk, Head of Events, lexi@kinvolk.io
Chris is a CNCF Ambassador and long-time open source contributor.
Lexi heads the events team at Kinvolk and coordinates volunteer and event diversity efforts.

### Organizer 2:
Kristin Wittig, Kubermatic, Head of Marketing and Communications, kristin@kubermatic.com

### Organizer 3: 
Tine Rehbein, SysEleven, Teamlead Marketing, tine@syseleven.de

Experience
We at Kinvolk already organize several successful open source events. We have put together three iterations of the All Systems Go!, the conference for foundational user-space Linux technologies. We have also put together 3 instances of the Cloud Native Rejekts conference, an event that offers a stage to some of the wonderful, but rejected, KubeCon proposals. We also organize the more than 1000 member strong CNCF Berlin Meetup.

Kinvolk focuses on putting on no-frills, engineer-oriented events and always looks forward to collaborating with others. This seems to be fully inline with what the CNCF is striving to do with KCD.

Kubermatic has organized Container Days in Hamburg and GoDays in Berlin. They bring lots of experience to the effort around all aspects of organizing community events.

### Sponsor 1
Kinvolk

### Sponsor 2
Kubermatic

### Sponsor 3
SysEleven

**Comment by cpanato** [comment]
cc @xmulligan @LexiNadolski

**Comment by tinerehbein** [comment]
@cpanato Thx for opening a new issue. The information from issue #177 can be taken over.

cc @LexiNadolski @KrissiWi

**Comment by xmulligan** [comment]
@cpanato thanks for opening this! Can you ping me again when you copy over the information so I can look it over again?

**Comment by LexiNadolski** [comment]
_Here is the copy of the information, updated_ @xmulligan 

**Event City: Berlin**
**Organizers 1:** Chris Kuehl, Kinvolk, CEO, chris@kinvolk.io + Lexi Nadolski, Kinvolk, Head of Events, lexi@kinvolk.io
Chris is a CNCF Ambassador and long-time open source contributor.
Lexi heads the events team at Kinvolk and coordinates volunteer and event diversity efforts.

**Organizer 2:** Kristin Wittig, Kubermatic, Head of Marketing and Communications, kristin@kubermatic.com

**Organizer 3:** Tine Rehbein, SysEleven, Teamlead Marketing, tine@syseleven.de

We'd like to propose an event in Berlin in March 2022. 

**Experience**
We at Kinvolk already organize several successful open source events. We have put together three iterations of the All Systems Go!, the conference for foundational user-space Linux technologies. We have also put together 3 instances of the Cloud Native Rejekts conference, an event that offers a stage to some of the wonderful, but rejected, KubeCon proposals. We also organize the more than 1000 member strong CNCF Berlin Meetup.

Kinvolk focuses on putting on no-frills, engineer-oriented events and always looks forward to collaborating with others. This seems to be fully inline with what the CNCF is striving to do with KCD.

Kubermatic has organized Container Days in Hamburg and GoDays in Berlin. They bring lots of experience to the effort around all aspects of organizing community events.

**Submission checklist:**
*Please check each of these indicating that you have met these requirements:

- [ ]  No other Kubernetes Community Day event in the same region
- [ ]  Minimum of 3 organizers from 3 different organizations
- [ ]  Every organizer has an account on Cloud Native Community Groups
- [ ]  Each organizer lives in or just outside of the KCD location
- [ ]  At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
- [ ]  All organizers agree to follow the event guidelines and CNCF Code of Conduct
- [ ]  Minimum of 3 sponsors committed
- [ ]  Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
- [ ]  Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
- [ ]  Agree to use Cloud Native Community Groups for registration, scheduling, and event website
- [ ]  Agree to use SM Apply for CFP
- [ ]  Event date and time has been chosen
- [ ]  Added usernames for CNCF Slack for all organizers so that we can add you to the #kcd-organizers channel
- [ ]  Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
- [ ]  Organizer email alias has been created
- [ ]  Region and event has been created in Bevy

Sponsor 1: Kinvolk
Sponsor 2: Kubermatic
Sponsor 3: SysEleven

**Method of accepting payment**
Stripe or bank transfer preferred.

**Comment by xmulligan** [comment]
@LexiNadolski thanks, I've updated the information above. For the "Fiscal sponsor that will accept payments" we need a company or organization that will be handling the payments not the method of accepting payments. Also will the event be in person, virtual, or hybrid?

**Comment by xmulligan** [comment]
I just wanted to follow up on this issue and see if you needed any help. Also in case you missed it KubeCon CloudNativeCon EU 2022 will be may 17-20 https://events.linuxfoundation.org/kubecon-cloudnativecon-europe-2022/

**Comment by LexiNadolski** [comment]
Hey @xmulligan, I am not sure about this yet. We will be having a meeting closer to the end of the summer to discuss all of this. We will let you know as soon as things are clear. We would like to have an in-person event which is why doing it next year made most sense. I think for the fiscal sponsor, we will need to chat at the meeting. Talk soon!

**Comment by cpanato** [comment]
@LexiNadolski i will wait some updates from you then I can update this issue :)

**Comment by xmulligan** [comment]
@LexiNadolski thanks for the update! I'll check back in once summer holidays are over. If anything comes up in the meantime, please feel free to reach out :)

**Comment by xmulligan** [comment]
Hi @LexiNadolski and @cpanato just wanted to check in with you before the end of the year. Is there anything you need from me to plan your KCD for next year?

**Comment by cpanato** [comment]
> Hi @LexiNadolski and @cpanato just wanted to check in with you before the end of the year. Is there anything you need from me to plan your KCD for next year?

I'm here to help but I don't have much power on the sponsors/place to help :( 
i think this is something that @LexiNadolski and the amazing team can help with

**Comment by LexiNadolski** [comment]
Hello @xmulligan I only came back from sick leave today after being away since October 22nd. It will take me some time to catch up. I will chat with the team to meet the first week of December so we can give you more information. Cheers!

**Comment by philwelz** [comment]
Hey all, maybe @Govinda-Fichtner can help with the location

cc @firecyberice

**Comment by Govinda-Fichtner** [comment]
@philwelz and all, I am happy to help out with a location. We just moved into a nice, new office in Berlin with lots of space for this kind of events. Any idea how many participants we are potentially going to host?

**Comment by xmulligan** [comment]
I've created your site here https://community.cncf.io/kcd-berlin/. It seems Tine doesn't have an account on the site yet though?

**Comment by join2ashish** [comment]
@xmulligan can you please let us know how we can connect the CFP portal(SM Apply) with our event? Do we need any other account for accessing that website?

**Comment by xmulligan** [comment]
@join2ashish I haven't created the CfP for the event yet. Before I can do that I need you to fill out the missing information in the issue template above including website and cfp dates and cfp admin. It would also be great to set up our monthly organizer check ins

**Comment by LexiNadolski** [comment]
@xmulligan we have checked off the lists below and please look at my comment above from April 7th which has also been updated. 

Let's figure out a date for a checkin with all orgs when you can. Thanks!

CfP open and close dates: February 9 - May 26, 2022
Website launch date: February 9, 2022

Submission checklist for CNCF:
 -[x] Organizer email alias has been created
 -[x] Region created in Bevy
 -[x] Added to Bevy header
 -[ ] CfP created
Post Event checklist:
-[ ]  Removed from Bevy header
-[ ]  CfP deactivated
-[ ] Videos uploaded to Youtube and linked to event page
Expected Number of Attendees: 400+

**Comment by philwelz** [comment]
hey @xmulligan , there is a spelling mistake here = https://community.cncf.io/events/details/cncf-kcd-berlin-presents-kubernetes-community-days-berlin-2022/

It is called "Insel der Jugend" instead of "Insel der Junge"

**Comment by tinerehbein** [comment]
@philwelz Thank you. I´ve changed the name.

**Comment by xmulligan** [comment]
@LexiNadolski sorry for the delay getting back to you on this. I've been out. Can you suggest some times next week that would work for the meeting? I'm also working on getting you access to the CfP platform

**Comment by cpanato** [comment]
@xmulligan @tinerehbein let me know what is missing in this issue to we have a final approval

**Comment by xmulligan** [comment]
@cpanato thanks for updating! I finally got access to the cfp and created the account. You all should have gotten an email to login as admins

**Comment by KrissiWi** [comment]
@xmulligan : Unfortunately, I have not gotton an email yet

**Comment by xmulligan** [comment]
@KrissiWi you should have it now.

**Comment by xmulligan** [comment]
@tinerehbein I've just resent it. Try logging it at https://kcd.smapply.io/. It should be to your tine@syseleven.de account

**Comment by tinerehbein** [comment]
> @tinerehbein I've just resent it. Try logging it at https://kcd.smapply.io/. It should be to your [tine@syseleven.de](mailto:tine@syseleven.de) account

@xmulligan I´m not allowed to set my confirmation password to set up my account. Could you pls add me with c.rehbein@syseleven.de? Then I can try to log in with my google account

**Comment by xmulligan** [comment]
@tinerehbein I've just sent it

**Comment by tinerehbein** [comment]
Thank you @xmulligan

**Comment by KrissiWi** [comment]
@xmulligan : Unfortunately, the organizers-berlin@kubernetescommunitydays.org email list is not working. Sandra (s.gramatzki@syselven.de), Ashish (mishraashish@microsoft.com), Lexi (lexinadolski@microsoft.com) and I (kristin@kubermatic.com) are not getting the incoming emails:/ Can you advise?

**Comment by xmulligan** [comment]
@KrissiWi I've updated the email forward to include all of you. Let me know if it works :)

**Comment by KrissiWi** [comment]
@xmulligan : Works for me:)

**Comment by KrissiWi** [comment]
Hi @xmulligan : Could you add Mira (mira@loovent.com) to the mailing list as well. She is (mostly) back from her maternity leave and will support KCD Berlin as well

**Comment by xmulligan** [comment]
@KrissiWi I've just added her. Tell her I say hi too :)

**Comment by KrissiWi** [comment]
@k8tgreenley : Hi Katie, in our website backend we can currently only differentiate between Gold, Silver and Community sponsors, meaning that Bronze is missing. I can't find any way to fix this on my own. Can you support?

**Comment by KrissiWi** [comment]
@k8tgreenley or @KTan1226 : can anyone help me with the issue mentioned aboce?

**Comment by k8tgreenley** [comment]
@KrissiWi thank you for letting me know that the Bronze level was missing. I have now added this type. Please let me know if there are any additional levels that need to be added.

**Comment by KrissiWi** [comment]
Thanks @k8tgreenley !

**Comment by k8tgreenley** [comment]
@LexiNadolski per our slack messaging with Benazir:

Thanks for checking, [@k8tgreenley](https://cloud-native.slack.com/team/U0Z8QKTL4), we need to send out email alerts to speakers for their upcoming talks at the event - in this email, we wanted to specify to speakers to upload their slides on the CNCF website. Attendees like to check them out sometimes.. as I see it, this is not an option for speakers to upload on the website themselves, correct? cc: [@Lexi Nadolski](https://cloud-native.slack.com/team/UCX8K437V)


[Katie Greenley - CNCF Events Team](https://app.slack.com/team/U0Z8QKTL4)  [7:16 AM](https://cloud-native.slack.com/archives/C03GS9CDBN2/p1655298980467089)
[@Benazir Khan](https://cloud-native.slack.com/team/U039XG1HNDD) [@Lexi Nadolski](https://cloud-native.slack.com/team/UCX8K437V) I am going to start moving our conversation over to the gihub issue to help track. I have spoken with bevy and the only way to add slides to the agenda is post event. Here is how they are added: https://help.bevy.com/hc/en-us/articles/1500001777382-Wrap-up-an-event. You can set up a slideshare and have the speakers upload there and then you add the link post event

Bevy Help CenterBevy Help Center
[Wrap up an event](https://help.bevy.com/hc/en-us/articles/1500001777382-Wrap-up-an-event)
This article outlines the event wrap up tab and what details you can add to completed events. To wrap up an event page: From the Chapter Dashboard, click Events from the left sidebar. Click the ...
[7:17](https://cloud-native.slack.com/archives/C03GS9CDBN2/p1655299039081479)
Unfortunately, this is not an ideal approach to uploading slides. I am noting this as one of the pain point with using the Bevy system. I am looking into changes for the program and are noting all the items that are not ideal at this very moment

**Comment by KrissiWi** [comment]
@k8tgreenley : Could you please add another sponsor/partner category / `Media Partner`? Thanks!

**Comment by k8tgreenley** [comment]
@KrissiWi this has been added
