### ISSUE TITLE
KCD Menu

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#4]
Menu - Non-event page - https://kubernetes-community-days.netlify.com/
Home page
Organizing

Menu - Event page
Example: https://kubernetes-community-days.netlify.com/events/santa-clara-2019/
Home page logo <take back to  https://kubernetes-community-days.netlify.com/>
Location
Program
Speakers
Sponsor
Contact
Code of conduct

**Comment by lucperkins** [comment]
@christinevblum This format is currently supported. Any page that you add in an event's directory (e.g. `content/events/santa-clara-2019` will show up in the navbar for that event. In this case, you only see a Sponsors page because that's the only page in that directory. If you added a Speakers page, it will show up.

**Comment by dankohn** [comment]
That's great functionality, BTW.
