### ISSUE TITLE
KCD 2022 Czech & Slovak virtual

### ISSUE THREAD

**Issue by georg007** [cncf/kubernetes-community-days#422]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location:
KCD 2022 Czech & Slovak virtual

### Event Date and Time:
27. and 28. april 2022

### Event type: 
virtual
two day event with two tracks Management (beginners) and PRO.

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [X] No other Kubernetes Community Day event in the same region 
* [X] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check in with KCD Core Organizer scheduled
* [X] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [X] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [X] Agree to use SM Apply for CFP
* [X] Event date and time has been chosen
* [X] Agree that there will not be an all male speaker lineup
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [X] Provided CNCF access to all event social handles

CfP open and close dates: Open 17th of January. Close: 15th of feburary 
Website launch date: 19th of January https://kcd.live

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Fiscal sponsor that will accept payments
NGO:
Združenie pre podporu Cloud Native technológií
ID NO (ICO): 52821595

**Comment by xmulligan** [comment]
@georg007 Thanks for opening this issue, I'm really excited to see this KCD coming to a new region! 🎊 Sorry for the delay getting back to you, I've been OOO for the holidays and won't actually be back until the new year, but didn't want you to have to wait that long. 
 
 It looks like the biggest things for you right now are: 1. finish collecting the other organizer information. once you have that I can add them to the correct channels 2. deciding on the dates for the cfp and website launch. once you have those I can create the accounts for you 3. scheduling a check in call with me https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-12
 
 Really looking forward to meeting you and your team!

**Comment by xmulligan** [comment]
Thanks for meeting with me today! Excited to see this event come together 🚀 

To follow up on our meeting:

- [ ] I'm getting you a course code for the Bevy training
* You probably won't make a Twitter because it is not that popular in your countries
* You can find an example sponsor prospectus here https://github.com/cncf/kubernetes-community-days/blob/main/content/templates.md#sponsor-prospectus 
* You can find post event reports here https://github.com/cncf/kubernetes-community-days/blob/main/content/templates.md#post-event-reports
* The max attendees can be found here https://help.bevy.com/hc/en-us/articles/360063609093-Maximum-attendee-and-presenter-limits-for-stages-sessions-networking-tables-and-booths
* You can see an example of recordings from Bevy at https://www.youtube.com/playlist?list=PLj6h78yzYM2M3cMd-zoDppjMo9eRmQrYU
- [ ] I'm working to get the webiste and CfP created for you
* we have our next meeting on February 1st

Let me know if you need anything in the meantime :)

**Comment by AudMonte01** [comment]
Hello @georg007  and team! I am the new KCD Program Manager for the CNCF and see the videos from your April event are not yet up on YouTube. If you would like for them to be added to a CNCF playlist, please let me know if you have a link to all of them that you can share with me. Otherwise, I can pull them down from Bevy (though it will take longer because some videos have multiple sessions within one). Thank you!

**Comment by georg007** [comment]
Hi, 

Here are the videos: https://www.youtube.com/playlist?list=PLzO-esMdGBjcux7K3mcSvGqvQYaNdQn9W

Best regards.

Juraj Hantak

**Comment by AudMonte01** [comment]
Thanks so much, George! I have saved this to the CNCF YouTube library.

Audra Montenegro
CNCF KCD Program Manager | About Kubernetes Community Days
<https://community.cncf.io/kubernetes-community-days/about-kcd/>
(707)-548-7635
US Time zone: Pacific
