### ISSUE TITLE
KCD Barcelona 2024 (June)

### ISSUE THREAD

**Issue by immavalls** [cncf/kubernetes-community-days#530]
# KCD Organizer Checklist

First in-person KCD Spain. Previous editions https://github.com/cncf/kubernetes-community-days/issues/510 in 2023, https://github.com/cncf/kubernetes-community-days/issues/440 in 2022 and https://github.com/cncf/kubernetes-community-days/issues/385 in 2021.

### Event Details
* [x] Event Location: Co-located with DevBcn in Barcelona, Spain
* [x] Event Date and Time: June 13-14, 2024
* [x] Expected Number of Attendees: 200-250 (KCD track). This is a co-located event at a 1000-attendee conference with several tracks: https://www.devbcn.com/
* [x] The event cost per ticket starts at €250 (blind) and keeps increasing to €500. Tickets are already available at https://tickets.devbcn.com/event/devbcn-2024, blind and early bird expired. We are now at regular price, €350.

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer:
* [x] Almudena Vivanco, SCRM, Principal Performance Engineer, [almudena.vivanco@gmail.com](mailto:almudena.vivanco@gmail.com), almudena vivanco
* [x] Ana Carmona, Adevinta, Sr. Engineer Manager, [ana.carmona.ag@gmail.com](mailto:ana.carmona.ag@gmail.com), Ana Carmona
* [x] Christian Polanco, Adevinta, Sr. DevOps Engineer, [polancochristian@gmail.com](mailto:polancochristian@gmail.com), Christian Polanco
* [x] David Ricordel, Elastic, Consulting Architect, [daverick.in.bcn@gmail.com](mailto:daverick.in.bcn@gmail.com), David Ricordel
* [x] Imma Valls, Grafana Labs, Developer Advocate, [imma.valls@gmail.com](mailto:imma.valls@gmail.com), Imma Valls
* [x] Jose Adan Ortiz, Roche, Platform Engineer, [joseadanof@gmail.com](mailto:joseadanof@gmail.com), Jose Adan Ortiz
* [x] Pablo Chacin, Grafana Labs, Tech Lead, [pablochacin@gmail.com](mailto:pablochacin@gmail.com), Pablo Chacin
* [x] Rael Garcia Arnés, Red Hat, Principal Software Engineer, [rael@redhat.com](mailto:rael@redhat.com), rael
* [x] Jose Lorenzo Castillo, Freelance, joselorenzocastilloc@gmail.com, Lorenzo

We'll add the full team soon once [KCD Spain 2023](https://community.cncf.io/events/details/cncf-kcd-spain-presents-kcd-spain-2023/) is done.

### Terms

* [x] No other Kubernetes Community Day event in the same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees that have opted in to their information being shared.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use Sessionize as the Call for Proposals (CFP) platform (team will provide CNCF access to DevBcn Sessionize account).
* [x] Agree to get logo creation and approval with and from CNCF. NOTE: a new logo will be created in an effort provide unity, and and official KCD stamp of approval.

The above questions might change a bit due to this being a co-located event:
- KCD Spain will be a track on https://www.devbcn.com/
- The conference already uses their own sessionize and talks will be sent to the same. @AudMonte01 is reviewing the CNCF CoC to see if the conference CoC https://www.devbcn.com/codeOfConduct is missing anything we should add.
- We are preparing the sponsorship slides that will include KCD Spain logo. Can we use the https://kcdspain.com/ logo or shall we adapt to the [new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link)?

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events). We do not have sponsors yet. However the [main event DevBcn](https://www.devbcn.com/) will take place with their own sponsorship or KCD, it's a long-running event (previously https://www.jbcnconf.com/2022/). We will be a track in the conference and do not need additional funding for KCD. 
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses: https://www.devbcn.com/
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a LinkedIn profile and/or Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used): https://twitter.com/KCDSpain

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: barcelona-organizers@kubernetescommunitydays.org 
* [x] Region created in Bevy
* [x] Added to Bevy header
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] <s>CFP deactivated</s>
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by rezuma** [comment]
Nice, would love to be there

**Comment by AudMonte01** [comment]
Hi folks - let's have an official kick-off meeting even though we chatted a little about this during the preparations of KCD Spain's virtual event in December. Could someone find time on my calendar that works for everyone? https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by immavalls** [comment]
Update on the KCD Barcelona status:

- The [DevBcn CoC](https://www.devbcn.com/codeOfConduct) was modified to add an e-mail to contact the CoC team.
- The KCD track has 130 talks already.
- We will need to create the event under https://community.cncf.io/, and are unsure if it should be a separate "KCD", KCD Barcelona, or if we shall reuse the KCD Spain group and create it there. This week we can probably discuss this at our kick-off meeting.

**Comment by AudMonte01** [comment]
KICK-OFF MEETING

Organizers
* Intros and roles
* David, José, Imma, and Rael have taken the [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

Content
* 130 talks submitted to the KCD
* Team will have a free booth there to talk about Cloud Native

Attendee goals
* 200-250 for the KCD track specifically 350 Euros for a ticket
* Free event in the future if this KCD is standalone
* Mostly professionals, and the team

Sponsorships
* DevCon Barcelona will be handling all sponsorships
* Thankfully diversity scholarship (tickets) are offered

Next steps
* Imma added Audra to organizer Slack channel
* [ ] Imma to create a draft event in Bevy using the "Meetup" event type
* [ ] Audra can point to page in KubeWeekly newsletter once page is LIVE

**Comment by immavalls** [comment]
Logos are [here](https://drive.google.com/file/d/17WIgY_9H61UbqrCVZ6jF7ghuPlNY1mQS/view?usp=drive_link).

**Comment by immavalls** [comment]
The call for speakers is closed, some stats in https://x.com/vilojona/status/1775062045852868829. The "cloud" track is KCD, and we got 267 talk proposals.

**Comment by AudMonte01** [comment]
APRIL 2 CNCF MONTHLY SYNC

Agenda is under review for KCD + DevBcn

Marketing
* Tickets are not an issue and the goal is 1000 in the end
* [ ] Imma will create a PR to request the KCD Barcelona logo replace the KCD Spain logo on the DevBcn website
* [ ] Team might consider a collaborative blog for KCD Spain

Sponsorships
* [ ] Imma to ask if we can point their prospectus in the KubeWeekly newsletter
-- If not, point to [sponsors@devbcn.com](mailto:sponsors@devbcn.com)

**Comment by immavalls** [comment]
Thanks @AudMonte01 the link to devbcn sponsorship brochure is in https://www.devbcn.com/sponsorship

**Comment by immavalls** [comment]
ongoing PR https://github.com/dev-bcn/dev-bcn.github.io/pull/388 to replace KCD Spain logo on the DevBcn website

**Comment by immavalls** [comment]
Changes merged @AudMonte01 , removed KCD Spain from https://www.devbcn.com/ and https://www.devbcn.com/kcd

**Comment by immavalls** [comment]
Diversity scholarship is published https://x.com/kcdspain/status/1785364476650303927?s=46&t=qf40Qc3xG-gn5alrp2Jnpw

**Comment by AudMonte01** [comment]
MAY 14 CNCF SYNC

Content
* Speakers are still under final selection
* KCD Team keep pushing DecBcn

Marketing
* Lorenzo is doing the marketing, and consistent 
* [x] Training vouchers for raffle. Audra to share via email

Tickets
* 3 candidates for diversity tickets, tickets sent on May 20

**Comment by immavalls** [comment]
We have already assigned 5 free diversity tickets. We are working with DevBcn to give away 3 more, as more folks applied than tickets. I am not sure if we'll be able to, though we can try.

We have the final speakers selected, and I'll send them to the [kcd@cncf.io](mailto:kcd@cncf.io) asap.

**Comment by AudMonte01** [comment]
CNCF CHECK-IN

Content
* All talks are from different organizations other than 2 Dynatrace
* Final lineup was decided by DevBarcelona

On-Site Logistics
* No emcees on stage per DevBcn
* Imma to remind to the team to be ready to emcee just in case. The DevBcn team decided last-minute previous times
* Just volunteers at the door

Marketing
* Gave away 5 diversity tickets on the KCD side, and DevBcn gave 7 more diversity tickets after
* Sold Out event
* New Barcelona social accounts are slowly building a following
* Posted about all speakers, with some amplifying
* Team to repost on [#socialmedia Slack channel](https://cloud-native.slack.com/archives/C12MRQ97A) ask Jessie Adams-Shore to repost

**Comment by immavalls** [comment]
The attendance was 700 people (from what DevBcn told us), and pictures are now available at https://www.flickr.com/photos/devbcn/collections/72157722904220482/

**Comment by AudMonte01** [comment]
JUNE 25 RETROSPECTIVE W/ CNCF

Positives feedback
* Engaging
* Multimedia was well done
* Financially easy / not responsible for overhead costs
* Were able to push diversity in speakers
* Great program committee for the KCD, and learned a lot on what it takes to produce good content. Good collaboration / common ground
* Some attendance from international people in the KCD room like Venezuela and Italy
* Some interest in participating in the community group

Lessons learned
* It felt more like they wanted CNCF as a sponsor versus KCD as a co-located event
* Did not use organizers as emcees, or even mention what a KCD is
* Could use better content
* The talks were biased towards sponsors (chosen by DevBcn). Frustrating after KCD team did valued reviewing
* Have this event for free next time
* DevBcn was not inclusive of KCD organizers on-site
* Lack of transparency in the entire process
* Will not partner with DevBcn in the future

Analytics
* Registrations versus check-ins (100 versus 700 for main event)
-- no room monitors
* Diversity rate: Non-male speakers - 31%
* Sponsorships were sold by DevBcn

Post-event marketing
* Photos linked above. No video recordings
* [ ] Imma submitted Credly badges for Audra to distribute to speakers
* [ ] Audra to share transparency report template with Imma to check with DevBcn team to see if they want to be part of it

**Comment by AudMonte01** [comment]
Hi @immavalls - all 14 speaker badges have been issued, and here is the [link to the transparency report template](https://www.canva.com/design/DAFhDHqyNBw/xz6Q0pxvfDBIbRljvjIRTw/watch?) for you to share with the DevBcn folks.

**Comment by icougil** [comment]
hi team,
Let me jump in here and add few notes, just to to add another POV/clarify few things. 
Best,

> JUNE 25 RETROSPECTIVE W/ CNCF
> 
> Positives feedback
> 
> * Engaging
> * Multimedia was well done
> * Financially easy / not responsible for overhead costs
> * Were able to push diversity in speakers
> * Great program committee for the KCD, and learned a lot on what it takes to produce good content. Good collaboration / common ground
> * Some attendance from international people in the KCD room like Venezuela and Italy
> * Some interest in participating in the community group
Great!

> Lessons learned
> 
> * It felt more like they wanted CNCF as a sponsor versus KCD as a co-located event
Well, this is a feeling could (or could not) match our feeling as the organizers of the DevBcn. It was clear that the responsibility of organizing the DevBcn and hosting KCD was entirely under DevBcn umbrella, right? We signed an agreement about it.

> * Did not use organizers as emcees, or even mention what a KCD is
First, it was not needed to have any member of KCD in the opening. Second, it was clear who where the organizers of the event that co-located KCD physically in the same venue. Third, did you organise anything? Organizer is somebody who organizes something, in this case, related with the physical event. 
Of course, we are not questioning the value of the work done by the KCD CFP committee (you did a great job, btw), but organising? I don't think the team organised anything around the physical event DevBcn - KCD, it wasn't the objective either, the organisation was clear who was in charge from minute 0.
Said that, yes, we know we made a mistake in the opening because we forgot to mention what KCD is. In the opening, we were in a rush at the beginning of the event because the registration was not as fast as we'd liked (probably you noticed that if you were there) and we could not spend too much time on it because after our speech the 1st keynote would start (and we couldn't steal a single minute for any speaker as you can imagine). In the closing we fixed that: we were more relaxed, without no time/speed constraints. Were any of you there? The recordings will demonstrate that in any case. 

> * Could use better content
We tried to do our best, but it is not economically affordable and sustainable (at least for us) to pay for travel & expenses for speakers that come far away from Barcelona (ex: Australia, US, etc) and even more difficult with less than 1 month before the event.

> * The talks were biased towards sponsors (chosen by DevBcn). Frustrating after KCD team did valued reviewing
Sorry, sponsors pushed for their content/talks and we tried to make the best balance we could VS the money they put into the event. 
About the reviewing process, we can imagine the frustration for the KCD CFP team,... but imagine as well the organization of DevBcn where we found many talks that we received ...and were not reviewed by the committee. I think here we had a miscommunication at some point... (and I know part of this problem is on me 😔, based on what I commented to @immavalls , but I thought it was evident that all talks should be reviewed by the entire committee...).

> * Have this event for free next time
What we can say? Good luck! 🙂👍

> * DevBcn was not inclusive of KCD organizers on-site
I don't understand this point: we signed an agreement where it was clear that we would deliver a stand for the KCD community to have the community there (the same we did with the rest of the communities we had in there, btw). Where is the non-inclusive part?

> * Lack of transparency in the entire process
Don't understand that as well.

> * Will not partner with DevBcn in the future
🤷‍♂️

> Analytics
> 
> * Registrations versus check-ins (100 versus 700 for main event)
Don't know what's a check-in, but yes, we had 705 attendees.

>   -- no room monitors
What does this mean?

> * Diversity rate: Non-male speakers - 31%
> * Sponsorships were sold by DevBcn
I hope you did not expect other results based on the organisation who invested -and risked- their money and financial sustainability and the agreement we signed, right?

> Post-event marketing
> 
> * Photos linked above. No video recordings
You haven't asked about recordings, did you? They are still post-processing, if you wait a few days, probably we will receive them and we will share them accordingly...

> * [x]  Imma submitted Credly badges for Audra to distribute to speakers
> * [x]  Audra to share transparency report template with Imma to check with DevBcn team to see if they want to be part of it

**Comment by AudMonte01** [comment]
Hello @icougil - thank you for your insights and comments.

I probably should have met with you to express CNCF expectations with KCDs. Most KCD events are stand-alone events, or in some cases like this, are co-located. Co-located events to us mean the KCD organizers are given 1 or 2 rooms to figure out logistics like:
* Unique registration, or least a check-box for the KCD event so the organizers can know how many people to expect
* The content with limited sponsored talks (less than 50%)
* The emcees introducing the day's content
* Housekeeping slides (highlighting breaks, thanking sponsors, and asking for attendees to fill out a feedback survey)
* Designated sponsors (perhaps set up in the room our just outside it), or no tables and sponsoring a speaker dinner or giveaways.
* A room monitor/volunteer checking badges at the door and counting attendance in the room for each talk. This addresses the "check-ins" or physical bodies in the room, versus registration of tickets
* KCD signage outside of the room

From my understanding, the DevBcn team did not want logistical help of the KCD organizers so the room felt more like a track versus a co-located event.

It would be awesome if there are video recordings of the those talks, and a playlist created for the KCD. If so, CNCF can help amplify it (duplicate it) in our YouTube channel to promote it to our subscribers.

Kind regards,

Audra Montenegro
CNCF Core KCD Program Manager
kcd@cncf.io

**Comment by icougil** [comment]
My fault, Audra, I completely forgot to reply to you 🤦‍♂️ and now that I'll have holidays... I found more time to answer you (sorry about it).
I will reply online and sorry for replying so late 😞
Best,

> Hello [@icougil](https://github.com/icougil) - thank you for your insights and comments.
> 
> I probably should have met with you to express CNCF expectations with KCDs. Most KCD events are stand-alone events, or in some cases like this, are co-located. Co-located events to us mean the KCD organizers are given 1 or 2 rooms to figure out logistics like:
> 
> * Unique registration, or least a check-box for the KCD event so the organizers can know how many people to expect
> * The content with limited sponsored talks (less than 50%)
> * The emcees introducing the day's content
> * Housekeeping slides (highlighting breaks, thanking sponsors, and asking for attendees to fill out a feedback survey)
> * Designated sponsors (perhaps set up in the room our just outside it), or no tables and sponsoring a speaker dinner or giveaways.
> * A room monitor/volunteer checking badges at the door and counting attendance in the room for each talk. This addresses the "check-ins" or physical bodies in the room, versus registration of tickets
> * KCD signage outside of the room

I see, well, I can understand all your rules and expectations that you would like to have for all the KCD events, but this is something we didn't know in advance. Also, from the other side, I see things that can collide with the organization/policies with the other event. There are many things that the organizers should know in advance, especially if the organizer is the one that assumes the economic cost of hosting the event, looking for sponsors, and ultimately financing itself, and the other event does not. IMHO, there seem quite a lot of demands for an event for which one organisation does not contribute a single euro, and another is the one who has to pay for everything...

> 
> From my understanding, the DevBcn team did not want logistical help of the KCD organizers so the room felt more like a track versus a co-located event.

Yes, that's true, because as a company, DevBcn never expected any help from the KCD team to organize anything around the logistics, venue, catering, etc. The entire organization of the event was always under the responsibility of DevBcn as it was shared in the agreement we signed.

> 
> It would be awesome if there are video recordings of the those talks, and a playlist created for the KCD. If so, CNCF can help amplify it (duplicate it) in our YouTube channel to promote it to our subscribers.

Oh yes! We uploaded the videos to our Youtube channel some time ago and we created a playlist too:
https://youtu.be/k7iMIXtNKyo?si=cK38hk4sYkirnqgx

> 
> Kind regards,
> 
> Audra Montenegro CNCF Core KCD Program Manager [kcd@cncf.io](mailto:kcd@cncf.io)

**Comment by AudMonte01** [comment]
Thank you for your reply, @icougil - no matter how delayed.

We understand the concern of the fiscal responsibility, which is why our KCDs typically handle (or could help in this case) with sponsorships too.

All in all, I feel like DevBCN could have at least leveraged the KCD organizers as an extra set of hands on-site, but that was not desired for whatever reason.

Thank you for sharing the playlist! We will amplify it as mentioned.

Kindest regards and happy holidays/end of the year to your and yours.
~ Audra Montenegro

**Comment by icougil** [comment]
Hi Audra,

I see. Well, now we understand much better that KCDs came with some "duties and responsibilities" that we didn't know before (and could come... with some presents as well).

Yep, I understand your point about having more volunteers help with many things during the event. But you probably also know that there are a lot of things to handle in an event and how to do them (documents to sign, rules to follow, security, etc.), and depending on how it could be more challenging to add more people than working with the team you already know.

Thank you for sharing the videos. I assume it will be great for all the speakers.

Merry Christmas and a Happy New Year to you and your beloved ones! 

PS: Let me know if, by any chance, you come to Barcelona. It will be great to have a coffee/tea with you in person someday ;-)
